### ISSUE TITLE
Measuring startup time

### ISSUE THREAD

**Issue by thearina** [inkdropapp/electron-v8snapshots-example#1]
Hi @craftzdog, could you, please, tell how did you measure your startup time, did you rely on the performance tab in devtools only ? 
If I run your test app, should I notice the time difference or is it too small for this ?
Thank you.

**Comment by craftzdog** [comment]
Yes, it will be too small to notice the difference for the test app.
I used the performance tab as I wrote in [the blogpost](https://blog.inkdrop.info/how-to-make-your-electron-app-launch-1000ms-faster-32ce1e0bb52c).
