### ISSUE TITLE
How to package

### ISSUE THREAD

**Issue by HZSamir** [inkdropapp/electron-v8snapshots-example#2]
Hello, and thank you for this example repo
Your example repo doesn't demonstrate how to package so how would that work? (Specifically with Electron-builder)
Copying the generated snapshot files directly into the released build breaks the app (Electron doesn't start and shows no error whatsoever)
Could I please trouble you for an example?
Thank you.

**Comment by LinDaiDai** [comment]
Have you solved this problem? If so, could you please tell me how to do the following? Thank you very much.

**Comment by LinDaiDai** [comment]
> Hello, and thank you for this example repo Your example repo doesn't demonstrate how to package so how would that work? (Specifically with Electron-builder) Copying the generated snapshot files directly into the released build breaks the app (Electron doesn't start and shows no error whatsoever) Could I please trouble you for an example? Thank you.

this

**Comment by HZSamir** [comment]
You can find a working repo based on Electron-react-boilerplate [here](https://github.com/Unforgiven-wanda/erb-mksnapshot-example).
A couple of notes:

- Add whatever dependencies you use to snapshot.js (in this case, React and React-dom)
- Set the exact version of Electron you're using in the `InstallDeps.js` script. In my case it is 16.0.5
- Run `installdeps` script from `release/app` folder with CMD, not powershell, or else the environment variable isn't set correctly)
- Run `generate-v8-snapshots` from that same folder. It should generate two files at the root of your project.
- Re-run `installdeps` and `generate-v8-snapshots` if your snapshot file changes, or your version of Electron in the future.
- In our package.json there is a `CopySnapshotBinToRelease.js`. This script will copy the generated snapshots into the app before it is packaged.

That's about it.
This was helpful when creating the various scripts. [Link](http://peterforgacs.github.io/2018/09/12/How-to-create-a-V8-snapshot-of-your-javascript-file/).
Just run `package-win` to create a Windows version showcasing this.
Hope it helps.

**Comment by LinDaiDai** [comment]
> 
Thank you so much. I'll try it.

**Comment by LinDaiDai** [comment]
> You can find a working repo based on Electron-react-boilerplate [here](https://github.com/Unforgiven-wanda/erb-mksnapshot-example). A couple of notes:
> 
> * Add whatever dependencies you use to snapshot.js (in this case, React and React-dom)
> * Set the exact version of Electron you're using in the `InstallDeps.js` script. In my case it is 16.0.5
> * Run `installdeps` script from `release/app` folder with CMD, not powershell, or else the environment variable isn't set correctly)
> * Run `generate-v8-snapshots` from that same folder. It should generate two files at the root of your project.
> * Re-run `installdeps` and `generate-v8-snapshots` if your snapshot file changes, or your version of Electron in the future.
> * In our package.json there is a `CopySnapshotBinToRelease.js`. This script will copy the generated snapshots into the app before it is packaged.
> 
> That's about it. This was helpful when creating the various scripts. [Link](http://peterforgacs.github.io/2018/09/12/How-to-create-a-V8-snapshot-of-your-javascript-file/). Just run `package-win` to create a Windows version showcasing this. Hope it helps.

Hello, sorry to bother you again.  This time I would like to ask you what happens when you use the electron-link to generate snapshot.js and some of the dependent modules depend on node.js native modules?  For example, IF I wanted to compile the electron-redux into a binary that relies on the fs module, I would get an error saying generating-v8-snapshots:  

Error: Cannot require module "fs".  
To use Node's require you need to call `snapshotResult.setGlobals` first!  

I found some schemes online, like: https://stackoverflow.com/questions/53857924/electron-mksnapshot-snapshotresult-setglobals-location
But in its terms I have some not too understand, because the execution of the generate-v8-snapshots is no snapshotResult object before, let alone to invoke snapshotResult.SetGlobals.  
So I would like to ask if you know how to solve this problem. Thank you very much.

**Comment by HZSamir** [comment]
Hello again.
I'm afraid I did not generate any native modules, so I haven't encountered this specific issue.
Sorry I can't help.

**Comment by LinDaiDai** [comment]
> Hello again. I'm afraid I did not generate any native modules, so I haven't encountered this specific issue. Sorry I can't help.

Yes, I think so, too. But thank you.
